### ISSUE TITLE
I tryed to use this but what ?

### ISSUE THREAD

**Issue by KoroFX** [JFryy/twist-moe-downloader#10]
Wtf ?
![image](https://user-images.githubusercontent.com/46395233/71375839-d45bf900-25bf-11ea-9f3c-d5f297cc1d02.png)

**Comment by Cyklan** [comment]
You are currently within the python interactive console (or whatever it may be called).
After installing twistdl with pip, just try running the `twistdl fate` command first thing in your command prompt

**Comment by JFryy** [comment]
As @Cyklan this is a cli tool ran in your shell environment.
