### ISSUE TITLE
Making current directory the default

### ISSUE THREAD

**Issue by Cyklan** [JFryy/twist-moe-downloader#11]
I really like the program, but there's one thing thats bugging me. When downloading and not specifying a directory, twistdl will always download to the `./anime` directory.
It had me confused when I suddenly had another anime folder within my anime folder.

**Comment by JFryy** [comment]
Hmm, I kind of prefer the default path being a directory entitled anime personally. I'll leave this issues open as I'm pretty open to changing this in the future if others find it frustrating as well.

**Comment by paulcsiki** [comment]
I agree with @JFryy, default should be dynamically constructed, if you want to download to a custom directory then there's an argument for that.

**Comment by JFryy** [comment]
Thank for your input @paulcsiki
