### ISSUE TITLE
error on installing

### ISSUE THREAD

**Issue by namaasliku** [JFryy/twist-moe-downloader#12]
i'm not sure what went wrong here

> ~$ pip install twistdl --user
> Collecting twistdl
>   Using cached https://files.pythonhosted.org/packages/18/88/71081197a98a3ed51d5bf9e8f2a7d2a40501d4d8cece3e4f7da74f88d3a2/twistdl-1.1-py2.py3-none-any.whl
> Collecting tqdm==4.40.2 (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/7f/32/5144caf0478b1f26bd9d97f510a47336cf4ac0f96c6bc3b5af20d4173920/tqdm-4.40.2-py2.py3-none-any.whl
> Collecting requests (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
> Collecting pycryptodomex==3.9.4 (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/45/7b/b86084ba5abec94055dd5997b57efa5bc4bc6114401c2011704895599892/pycryptodomex-3.9.4-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting pathlib2==2.3.5 (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
> Collecting six==1.13.0 (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
> Collecting PyInquirer==1.0.3 (from twistdl)
>   Using cached https://files.pythonhosted.org/packages/fb/4c/434b7c454010a284b49d6f1d446fe8dc5960415613d8c0225b9e2efb6724/PyInquirer-1.0.3.tar.gz
> Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->twistdl)
>   Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
> Collecting chardet<4,>=3.0.2 (from requests->twistdl)
>   Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
> Collecting certifi>=2017.4.17 (from requests->twistdl)
>   Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
> Collecting idna<3,>=2.5 (from requests->twistdl)
>   Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
> Collecting scandir; python_version < "3.5" (from pathlib2==2.3.5->twistdl)
>   Using cached https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
> Collecting Pygments>=2.2.0 (from PyInquirer==1.0.3->twistdl)
>   Using cached https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl
> Collecting prompt_toolkit==1.0.14 (from PyInquirer==1.0.3->twistdl)
>   Using cached https://files.pythonhosted.org/packages/4b/85/58829b76140b81b30d2d455040808665b2041b923134a287643b684de4e3/prompt_toolkit-1.0.14-py2-none-any.whl
> Collecting regex>=2016.11.21 (from PyInquirer==1.0.3->twistdl)
>   Using cached https://files.pythonhosted.org/packages/e8/76/8ac7f467617b9cfbafcef3c76df6f22b15de654a62bea719792b00a83195/regex-2020.2.20.tar.gz
> Collecting wcwidth (from prompt_toolkit==1.0.14->PyInquirer==1.0.3->twistdl)
>   Using cached https://files.pythonhosted.org/packages/58/b4/4850a0ccc6f567cc0ebe7060d20ffd4258b8210efadc259da62dc6ed9c65/wcwidth-0.1.8-py2.py3-none-any.whl
> Building wheels for collected packages: PyInquirer, scandir, regex
>   Running setup.py bdist_wheel for PyInquirer ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lVZ4d2/PyInquirer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpByhIYWpip-wheel- --python-tag cp27:
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for PyInquirer
>   Running setup.py clean for PyInquirer
>   Running setup.py bdist_wheel for scandir ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lVZ4d2/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpSz_MDKpip-wheel- --python-tag cp27:
>   /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
>     warnings.warn(msg)
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for scandir
>   Running setup.py clean for scandir
>   Running setup.py bdist_wheel for regex ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lVZ4d2/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpygtg3Cpip-wheel- --python-tag cp27:
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for regex
>   Running setup.py clean for regex
> Failed to build PyInquirer scandir regex
> Installing collected packages: tqdm, urllib3, chardet, certifi, idna, requests, pycryptodomex, six, scandir, pathlib2, Pygments, wcwidth, prompt-toolkit, regex, PyInquirer, twistdl
>   Running setup.py install for scandir ... done
>   Running setup.py install for regex ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lVZ4d2/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fUBZ2y-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/regex
>     copying regex_2/__init__.py -> build/lib.linux-x86_64-2.7/regex
>     copying regex_2/regex.py -> build/lib.linux-x86_64-2.7/regex
>     copying regex_2/_regex_core.py -> build/lib.linux-x86_64-2.7/regex
>     copying regex_2/test_regex.py -> build/lib.linux-x86_64-2.7/regex
>     running build_ext
>     building 'regex._regex' extension
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/regex_2
>     x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-5Z483E/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
>     regex_2/_regex.c:48:10: fatal error: Python.h: No such file or directory
>      #include "Python.h"
>               ^~~~~~~~~~
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lVZ4d2/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fUBZ2y-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-lVZ4d2/regex/

**Comment by JFryy** [comment]
I think it may be related to this issue:
https://github.com/huggingface/transformers/issues/932
