### ISSUE TITLE
can't seem to download episodes 100+

### ISSUE THREAD

**Issue by aq2oo3** [JFryy/twist-moe-downloader#14]
Whenever I try to download episodes past the 100 mark it says it's an "invalid input"
<img width="571" alt="Screen Shot 2020-06-12 at 10 43 41 AM" src="https://user-images.githubusercontent.com/51223506/84531578-a7002600-ac99-11ea-9b71-b9a019f2ea0f.png">
This is the same for when I try to get an episode range between the 90s and the 100s
<img width="339" alt="Screen Shot 2020-06-12 at 10 45 19 AM" src="https://user-images.githubusercontent.com/51223506/84531716-d6af2e00-ac99-11ea-9189-e1778e04f023.png">

**Comment by JFryy** [comment]
Hi @aq2oo3, I think you are using an older version of the package. If you get the latest version you should be able to use the cli and episode range option like so:
```
❯❯❯ twistdl hunter                                                                                                                                                                                                          ✘ 1
? Anime(s) found. Please choose a series to download:  Hunter x Hunter (2011)
Episode selection between 1-148. To download a range enter "1-5", for a single episode enter "5" or leave it empty press "Enter" to download all episodes.
Input: 100-101
anime/hunter-x-hunter-2011/Hunter x Hunter (2011) - 100.mp4:   6%|████████▍                                                                                                                                  | 31/508 [00:23<03:04,  2.58MB/s]
```
