### ISSUE TITLE
only downloading empty files into the wrong directory

### ISSUE THREAD

**Issue by TimBenninghoff** [JFryy/twist-moe-downloader#15]
I'm pretty sure this is my own mistake, but first of all, to actually launch the program I have to go into the client directory - within cmd - and use the "py twistdl" or "python twistdl" command there (WITHOUT the - between twist-dl and WITHOUT the .py ending. guess it was renamed at some point, but the tutorial wasn't adjusted. Or I'm just missing something). This is less of an actial issue and more of a "this is something that would have been nice to be spelled out since beginners like me try around for hours before finding it out themselves" :/

However not that I've actually gotten the program to download something, it ended up ignoring the path I specified. It just created a new folder cli/anime/nameOfAnime. And in there it saves a file with a very short name. For the example you've shown at the bottom of your readme: when downloading "code-geass-hangyaku-no-lelouch-r2", the file within the folder is just named "Code Geass". It has no ending, is 0KB large and obviously useless.

So in the end, I haven't gotten the program to really work. I have used the install command successfully initially, so I think that's not the problem. And I just noticed that you can attach files, so I tried that, but "We don't support that file type".

I'd be really glad if you could help me out and either tell me what I've done wrong here, or fix whatever is broken^^'

**Comment by JFryy** [comment]
Hi @TimBenninghoff, sorry about the issues, that sounds really frustrating!

Thanks for bringing up the issue with the `--directory` argument, this functionality was broken after a refactor of the script but is now fixed. Are you using Windows CMD? Also what version of the tool are you using? (You can verify this with `sudo pip freeze | grep twistdl` or `sudo pip3 freeze | grep twistdl`. If you are not using `1.1` or `1.2` I really suggest reinstalling this via pip through the `uninstall`/`install` commands. I have not experienced issues of failure to download files on mac or linux machines unfortunately, however if these issues persist for you on windows I can take a look into it. Sorry about that :(

**Comment by TimBenninghoff** [comment]
Sorry for not answering for a while. I think I used the lastest downloadable version to be sure compatibility issues are less likely. By now I unfortunately got another downloader to work, so there's no more feedback or answers I can provide retrospectively (as I don't remember the details). I'm sorry about that^^'
Thank you so much for your detailed answer though! :)
