### ISSUE TITLE
Class based / API

### ISSUE THREAD

**Issue by Nachtalb** [JFryy/twist-moe-downloader#6]
Would you be ok with if I refactored your code to be class-based and provide a python API? So that in the end, another program could do something like this:
```python
from twistdl import TwistDl

# Download first episode of all fate animes
client = TwistDl()
for anime in client.search_animes('fate'):
	anime.download(from=1, to=1, '/to/some/path/{}'.format(anime.id))
```

I would, of course, make sure that the CLI stays the same.

**Comment by JFryy** [comment]
Yeah that sounds great, I'll look to see if there are other methods we could add for programmatic usage when you're done with your refactor.

After we got this to a good state in terms of modularization I'll make this a pip package and cli installable to PATH of the user as well. Thanks for all the fabulous contributions.

**Comment by Nachtalb** [comment]
I'll do that tomorrow

And thanks for the initial package :+1:

**Comment by Nachtalb** [comment]
#7
